version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - "rabbit:rabbit"
    volumes:
      - .:/code
      - logvolume01:/var/log
  model:
    build: ./model
    ports:
      - "5001:5001"
  process_unit:
    build: ./proc
    links:
      - "web:web"
      - "model:model"
      - "rabbit:rabbit"
  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
volumes:
  logvolume01: {}